services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tourze\FaceDetectBundle\Controller\:
    resource: '../../Controller/'
  Tourze\FaceDetectBundle\Repository\:
    resource: '../../Repository/'
  Tourze\FaceDetectBundle\Service\:
    resource: '../../Service/'
    public: true
